name: sanad
description: "تطبيق سند التعليمي"
publish_to: 'none'
version: 1.1.0+4

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pdfrx: ^2.4.1
  google_generative_ai: 0.4.7
  intl: ^0.20.2
  shared_preferences: ^2.5.5
  image_picker: ^1.2.2
  rename: ^3.1.0
  supabase_flutter: ^2.15.0
  google_mobile_ads: ^9.1.0
  in_app_purchase: ^3.2.0
  share_plus: ^13.1.0
  url_launcher: ^6.3.2
  package_info_plus: ^10.1.0
  device_info_plus: ^13.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/logo/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/auth/
    - assets/icons/stages/
    - assets/icons/subjects/
    - assets/icons/logo/
    - assets/pdfs/subjects/
    - assets/jsons/tips.json
    - assets/jsons/Content/Preparatory/Islamic/
    - assets/jsons/Content/Preparatory/Arabic/
    - assets/jsons/Content/Preparatory/English/
    - assets/jsons/Content/Preparatory/Islamic/Ministerial/
    - assets/jsons/Content/Preparatory/Arabic/Ministerial/
    - assets/jsons/Content/Preparatory/Arabic/Ministerial/rules/
    - assets/jsons/Content/Preparatory/Arabic/Ministerial/literature/
    - assets/jsons/Content/Preparatory/Arabic/Ministerial/criticism/
    - assets/jsons/Content/Preparatory/English/Ministerial/
    - assets/jsons/Content/Scientific/Mathematics/Ministerial/
    - assets/jsons/Content/Scientific/Physics/Ministerial/
    - assets/jsons/Content/Scientific/Chemistry/Ministerial/
    - assets/jsons/Content/Scientific/Biology/Ministerial/
    - assets/jsons/Content/Scientific/French/Ministerial/
    - assets/jsons/Content/Literary/Mathematics/Ministerial/
    - assets/jsons/Content/Literary/History/Ministerial/
    - assets/jsons/Content/Literary/Geography/Ministerial/
    - assets/jsons/Content/Literary/Economics/Ministerial/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/tajawal-black.ttf
        - asset: assets/fonts/tajawal/tajawal-bold.ttf
        - asset: assets/fonts/tajawal/tajawal-extrabold.ttf
        - asset: assets/fonts/tajawal/tajawal-extralight.ttf
        - asset: assets/fonts/tajawal/tajawal-light.ttf
        - asset: assets/fonts/tajawal/tajawal-medium.ttf
        - asset: assets/fonts/tajawal/tajawal-regular.ttf
